language: ruby
before_install:
  - gem update bundler
  - bundle version
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1-head
  - ruby-head
  - jruby-19mode

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
